### ISSUE TITLE
When unavailable page does not render, changed locations and does not render

### ISSUE THREAD

**Issue by ghost** [justnat3/weatherapp#4]
![image](https://user-images.githubusercontent.com/68233531/87310268-5b80a800-c4e3-11ea-9fc3-868085aab55e.png)

Believe the app breaks when the WeatherAPI-service can not read in the description value.

**Comment by justnat3** [comment]
![image](https://user-images.githubusercontent.com/58314490/87856068-fca3a000-c8e1-11ea-85a8-a2fd93c23474.png)

Merged to master error on no description. added another condition to the reduce statement in mapdash.ts to resolve this issue.


`      this.block = this.res.alert.reduce(() => {
        description: this.block.main
        }) 
      if (this.block.description == 'clear sky') {
        return this.block.description = 'clear skys'
        }
      else {
        return this.block.description = 'No Info' 
      }
    });
  }`
